id = "zoya"
name = "Zoya"
version = "0.1.0"
schema_version = 1
description = "Zoya language support for Zed"
authors = ["Paul Chavard"]
repository = "https://github.com/tchak/zoya"

[grammars.zoya]
repository = "https://github.com/tchak/zoya"
rev = "0109726b9cf2fbfda82a89b22a478e60d5bf78f8"
path = "editors/tree-sitter-zoya"
